name: CI Check

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Say Hello from CI
      run: echo "✅ Code is built and ready!"
